### ISSUE TITLE
request for Tarsier2-7B Model

### ISSUE THREAD

**Issue by zwx08** [bytedance/tarsier#12]
Hello，I can't find the model of Tarsier2-7B for local
Thank you

**Comment by jwwang424** [comment]
Sorry, Tarsier2-7B is not open-source available (see https://github.com/bytedance/tarsier/issues/7).

**Comment by zwx08** [comment]
> Sorry, Tarsier2-7B is not open-source available (see #7).抱歉，Tarsier2-7B 不是开源的（请参阅 #7 ）。

I can understand that choice. Thank you for your answer.
